proxies:
  - {name: ðŸŽ¬ é¥­é¥­äº‘ NETFLIX âšˆâšˆâšˆâšˆâšˆâšˆ, server: tcp.aga01.fanfanyun1.club, port: 80, type: vmess, uuid: b04693ca-b5e1-316a-851f-e1cd026cd574, alterId: 2, cipher: auto, tls: false, network: ws, ws-path: /fanfanyun, ws-headers: {Host: a.189.cn}, udp: true}
